host: "localhost"
web_socket_port: ":8001"
port: ":3000"
accuracy: 6
eps: 1.0e-07
tick_size: 30
player_halfrect: 0.5
respawn_ticks: 250
tickDeleayRange: 100
game_statuses: {running: 0, finished: 1}
def_game: {
  consts: {accel: 0.05, friction: 0.05, maxVelocity: 0.7, gravity: 0.05},
  weapons: {
    K: {velocity: 0.99, damage: 10, latency: 1},
    P: {velocity: 0.9, damage: 10, latency: 3},
    M: {velocity: 0.99, damage: 7, latency: 1},
    R: {velocity: 0.5, damage: 50, latency: 10, radius: 3},
    A: {velocity: 0.99, damage: 100, latency: 20},
  },
  maxHP: 100
}
